# 游빐 Configuraci칩n de Railway
# Indica que el backend est치 en la carpeta "carpeta1_backend"
# e ignora las dem치s carpetas (frontend y textos)

[build]
builder = "NIXPACKS"
root = "carpeta1_backend"

# Entorno de compilaci칩n
[build.env]
NODE_ENV = "production"

# Ignorar carpetas que no deben incluirse en el build
[build.ignore]
paths = ["carpeta2_enlaces_api", "carpeta3_frontend"]

# Instrucciones de despliegue
[deploy]
buildCommand = "npm install"
startCommand = "npm start"
