# Railway configuration file
# Indica que el código Node.js está dentro de carpeta1_backend

[build]
builder = "NIXPACKS"
root = "carpeta1_backend"

[build.env]
NODE_ENV = "production"

[deploy]
buildCommand = "npm install"
startCommand = "npm start"
